# Generated by Django 3.0.3 on 2020-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.SlugField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriversCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.TextField(verbose_name='Необхідні документи')),
                ('category', models.CharField(max_length=2, verbose_name='Категорії навчання')),
                ('program', models.TextField(verbose_name='Програма навчання')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введіть ваше ім'я", max_length=20, verbose_name="Ім'я")),
                ('email', models.CharField(help_text='Введіть email', max_length=150, unique=True, verbose_name='E-mail')),
                ('text', models.TextField(help_text='Введіть текст відгуку', verbose_name='Текст відгуку')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
    ]
