# Generated by Django 3.0.3 on 2020-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chptautoschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeducation',
            name='name',
            field=models.CharField(default='Технікум', max_length=100),
        ),
    ]
