# Generated by Django 3.0.3 on 2020-02-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chptautoschool', '0003_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
    ]
