# Generated by Django 3.0.3 on 2020-02-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chptautoschool', '0004_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_phone',
            field=models.ManyToManyField(to='chptautoschool.ContactPhone', verbose_name='Контактний телефон'),
        ),
    ]
