# Generated by Django 3.0.3 on 2020-02-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chptautoschool', '0006_auto_20200214_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactphone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефони'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.RemoveField(
            model_name='baseeducation',
            name='url',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='url',
        ),
        migrations.RemoveField(
            model_name='driverscourses',
            name='url',
        ),
        migrations.RemoveField(
            model_name='respond',
            name='url',
        ),
        migrations.RemoveField(
            model_name='useful',
            name='url',
        ),
    ]
